### ISSUE TITLE
Time located in the text box in Safari web 

### ISSUE THREAD

**Issue by heddaway** [stagecast/bug-report#2] opened 2018-10-30 13:30 UTC
**Describe the bug**
When I write a message moment, the time of when the moment shall be sent is located in the mobil simulation to the left. 

**To Reproduce**
In the moment setup screen, do a telegram moment. 

**Expected behavior**
- 

**Screenshots**
<img width="1280" alt="screen shot 2018-10-30 at 11 10 11 am" src="https://user-images.githubusercontent.com/44610147/47721303-1bff2300-dc50-11e8-890f-7c6de2afa7b5.png">

**Desktop (please complete the following information):**
 - Safari 

**Additional context**
Taco hej

**Comment by mawlle** [comment] 2018-11-06 09:55
We know that there are some flaws on the platform when using FIrefox and safari.

This should be part of an update on how we handle other these browsers.

**Comment by filippoboiani** [comment] 2018-11-21 09:53
Not able to reproduce. Closing for now.

**Closed by filippoboiani** 2018-11-21 09:53 UTC
Labels: bug, web
