### ISSUE TITLE
Collage moment - picture not shown

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#9] opened 2018-11-08 08:48 UTC
**Describe the bug**
When I take a picture in the collage moment in the Android client - it doesn't appear in the "view"-window.

**To Reproduce**
0. Launch a collage moment
1. Take a picture in the collage moment from the android client
2. On webplatform: Press "view" on the collage moment

**Expected behavior**
I expect to see the picture that was taken in my browser.

**Desktop (please complete the following information):**
production - chrome

**Smartphone (please complete the following information):**
Android - marshall. Apk from Onur.

**Comment by peffis** [comment] 2018-11-08 10:33
I don't have an Android to test with unfortunately, but I tested it with iOS now and the picture appears. See for instance: https://www.stagecast.se/media/collage2.html?event=9C27A193-3F48-4961-9C18-7A038444069A&tag=F074055F-436F-4A15-B02E-0FD4A07B19F4

Worth noting is that the collage searches for content that is tagged - in this case with the tag F074... so it is important that the content is tagged in order for it to show up. I suspect you tested it with "Markus test event" Markus (?) and if so there is only two photos there that are tagged, which can be seen here: https://www.stagecast.se/media/collage2.html?event=2A76C2AE-9B42-4D60-B074-F34A122440EF&tag=4F701A3D-95CE-4117-9A51-47942F87C1E5 

These two I know that I have taken with my iOS phone (don't ask me why the phone "took" those pictures though because that's another bug). So I suspect that that Android phone simply does not tag the content. 

If you remove the tag option from the url and go instead to https://www.stagecast.se/media/collage2.html?event=2A76C2AE-9B42-4D60-B074-F34A122440EF
You will see more pictures. Is any of those the pictures that are "missing" Markus? If so we know that the Android does not tag pictures when uploading to collage moment and since the web frontend explicitly opens a page that looks for tagged content...then...

**Comment by mawlle** [comment] 2018-11-08 11:02
It's seems to be as you thought with the tagging of pictures from Android Stefan. 
I can see the pictures i take if I remove the ....&tag=.... from the url.
@onuryuxcodes First step should be to look over the tagging of the picture then.

**Comment by filippoboiani** [comment] 2018-11-08 11:30
Removing the web tag as the platform has only the role of redirecting to that url.

**Comment by fredrik-jarnbrost** [comment] 2018-11-20 10:04
Can not reproduce. Closing.

**Closed by fredrik-jarnbrost** 2018-11-20 10:04 UTC
Labels: android, high prio
