### ISSUE TITLE
SDK automatic flash moment.

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#141] opened 2019-01-16 10:22 UTC
**Describe the bug**
In the flash moment with settings automatic, I'm able to tap the screen to flash the light.
This is not the intended behavior.

It's either that the flash is automatic - no user input OR manual - only user input.

@Robin9224 correct me if i'm wrong here

**To Reproduce**
1. Set up a flash moment with automatic flashes
2. When moment is active on the phone - tap the screen
3. See error: This makes the flash go off.

**Expected behavior**
Not allowing user input when having automatic flash set up.

**Smartphone (please complete the following information):**
 - Device: iphone6
 - OS: 11.2.1
 - Version testflight stagecastSDK 1.0 build 5.0

***
- Add relevant label (ex if WEB -> add label "web" etc.)

**Comment by Robin9224** [comment] 2019-01-16 10:23
agree

**Comment by peffis** [comment] 2019-01-16 17:38
Duplicate of #147. Closing.

**Closed by peffis** 2019-01-16 17:38 UTC
Labels: bug, sdk
